services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "9229-9230:9229-9230"
    volumes:
      - .:/app
      - /app/node_modules # Keep modules inside the container to avoid conflicts with Windows
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/saas_db
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--inspect=0.0.0.0:9229

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: saas_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
